language: node_js
node_js:
  - "0.10"
sudo: false
install:
  - npm install
script: "./node_modules/.bin/grunt ci"

notifications:
  webhooks:
    urls:
      - "https://webhooks.gitter.im/e/6ae8a9996354c8026bc3"
    on_success: change
    on_failure: always
    on_start: false
